# Generated by Django 4.2.3 on 2023-07-23 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('RF', 'Receitas'), ('GF', 'Gastos Fixos'), ('GV', 'Gastos Variáveis'), ('I', 'Investimentos')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('montante', models.DecimalField(decimal_places=2, max_digits=8)),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.subcategoria')),
            ],
        ),
    ]
