# Generated by Django 4.2.3 on 2023-07-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_transacao_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(choices=[('Receitas', 'Receitas'), ('Gastos Fixos', 'Gastos Fixos'), ('Gastos Variáveis', 'Gastos Variáveis'), ('Investimentos', 'Investimentos')], max_length=50),
        ),
    ]
